name: Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".dist/**"

permissions:
  issues: write
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: 👇 Checkout
        uses: actions/checkout@v3

      - name: 🧪 Test
        run: yarn test

      - name: 🧱 Build
        run: yarn build

      - name: 📌 Commit & Push
        uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          commit_message: "chore: updates dist zip"
