name: Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/**"
      - "jest.config.js"
      - "package.json"
      - "src/**"
      - "tests/**"
      - "tsconfig.json"
      - "webpack.config.ts"
      - "yarn.lock"

permissions:
  issues: write
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  continuous-deployment:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - name: 👇 Checkout
        uses: actions/checkout@v3

      - name: 🤹 Instal Deps
        run: yarn install

      - name: 🧪 Test
        run: yarn test

      - name: 🧱 Build
        run: yarn build

      - name: 📌 Commit & Push
        uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          commit_message: "chore: updates dist zip"
